spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.42.150.233:3306/slip?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: 123456
    druid:
      filter: stat,wall,log4j,mergeStat,mergeStat2
      web-stat-filter:
        enabled: true
        url-pattern: /*

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: 123456


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    cache: false
#    prefix: classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xjtlu.slip.pojo
