
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.42.150.233:3306/slip?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    cache: false
#    prefix: classpath:/templates/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
#  mapper-locations: classpath*:**/**/**/mapper/*.yml
  type-aliases-package: com.xjtlu.slip.pojo
